import axios from "axios";
import html2pdf from "html2pdf.js";

function PdfCreate({ patient, pdfname, type }) {
  // =====================================================
  // DOCTOR PDF
  // =====================================================

  const downloadDoctorPDF = () => {
    if (!patient?._id) {
      alert("Patient data not available");
      return;
    }

const pdfUrl = `http://localhost:5000/api/patient/${patient._id}/pdf`;

    window.open(pdfUrl, "_blank");
  };

  // =====================================================
  // LAB BILL PDF
  // =====================================================

  // =====================================================
  // LAB BILL PDF
  // =====================================================

  const downloadLabBillPDF = async () => {
    if (!patient?._id) {
      alert("Patient data not available");
      return;
    }

    try {
      const res = await axios.get(
        `http://localhost:5000/lab/bill/${patient._id}`
      );

      if (!res.data?.success || !res.data?.bill) {
        alert("Lab bill not found");
        return;
      }

      const bill = res.data.bill;

      let testRows = "";

      (bill.tests || []).forEach((test) => {
        testRows += `
        <tr>
          <td style="border:1px solid #000;padding:8px;">
            ${test.testName || "N/A"}
          </td>

          <td style="border:1px solid #000;padding:8px;text-align:right;">
            ₹${test.price || 0}
          </td>
        </tr>
      `;
      });

      const element = document.createElement("div");

      element.style.padding = "30px";
      element.style.fontFamily = "Arial";

      element.innerHTML = `
      <h2 style="text-align:center;">
        Lab Bill
      </h2>

      <hr />

      <h3>Patient Details</h3>

      <p>
        <b>UHID:</b> ${bill.uhid || patient.uhid || "N/A"}
      </p>

      <p>
        <b>Name:</b> ${bill.patientName || patient.name || "N/A"}
      </p>

      <p>
        <b>Mobile:</b> ${bill.mobile || patient.mobile || "N/A"}
      </p>

      <p>
        <b>Doctor:</b> ${bill.doctorName || "N/A"}
      </p>

      <hr />

      <h3>Lab Tests</h3>

      ${testRows
          ? `
            <table
              style="
                width:100%;
                border-collapse:collapse;
                margin-top:10px;
              "
            >
              <thead>
                <tr>
                  <th style="border:1px solid #000;padding:8px;">
                    Test
                  </th>

                  <th style="border:1px solid #000;padding:8px;">
                    Amount
                  </th>
                </tr>
              </thead>

              <tbody>
                ${testRows}
              </tbody>
            </table>
          `
          : "<p>No lab tests available</p>"
        }

      <hr />

      <h3 style="text-align:right;">
        Total Amount: ₹${bill.totalAmount || 0}
      </h3>

      <p>
        <b>Payment Mode:</b>
        ${bill.paymentMode || "N/A"}
      </p>

      <p>
        <b>Payment Status:</b>
        ${bill.paymentStatus || "N/A"}
      </p>

      <p>
        <b>Bill Date:</b>
        ${bill.createdAt
          ? new Date(bill.createdAt).toLocaleString("en-IN")
          : "N/A"
        }
      </p>

      <hr />

      <p style="text-align:center;">
        Generated By HMS
      </p>
    `;

   createPDF(
  element,
  `${bill.patientName || patient.name || "Patient"}_Lab_Bill.pdf`,
  "portrait"
);

    } catch (error) {
      console.log("Lab Bill PDF Error:", error);

      if (error.response?.status === 404) {
        alert("Lab bill not found for this patient");
      } else {
        alert("Failed to generate Lab Bill PDF");
      }
    }
  };

  // =====================================================
  // PHARMACY PDF
  // =====================================================

  const downloadPharmacyPDF = async () => {
    if (!patient?._id) {
      alert("Patient data not available");
      return;
    }

    try {
      const res = await axios.get(
        `http://localhost:5000/api/pharmacy/bill/latest/${patient._id}`,
      );

      if (!res.data?.success || !res.data?.data) {
        alert("Pharmacy bill not found");
        return;
      }

      const bill = res.data.data;

      const patientData = bill.patientId || patient;

      let medicineRows = "";

      (bill.medicines || []).forEach((medicine) => {
        medicineRows += `
          <tr>
            <td style="border:1px solid #000;padding:8px;">
              ${medicine.medicineName || medicine.itemName || medicine.name || "N/A"}
            </td>

            <td style="border:1px solid #000;padding:8px;text-align:center;">
              ${medicine.quantity || 0}
            </td>

            <td style="border:1px solid #000;padding:8px;text-align:right;">
              ₹${medicine.price || medicine.unitPrice || 0}
            </td>

            <td style="border:1px solid #000;padding:8px;text-align:right;">
              ₹${medicine.amount || 0}
            </td>
          </tr>
        `;
      });

      const element = document.createElement("div");

      element.style.padding = "30px";
      element.style.fontFamily = "Arial";

      element.innerHTML = `
        <h2 style="text-align:center;">
          Pharmacy Bill
        </h2>

        <hr />

        <h3>Patient Details</h3>

        <p>
          <b>UHID:</b> ${patientData.uhid || "N/A"}
        </p>

        <p>
          <b>Name:</b> ${patientData.name || "N/A"}
        </p>

        <p>
          <b>Age:</b> ${patientData.age || "N/A"}
        </p>

        <p>
          <b>Gender:</b> ${patientData.gender || "N/A"}
        </p>

        <p>
          <b>Mobile:</b> ${patientData.mobile || "N/A"}
        </p>

        <p>
          <b>Doctor:</b> ${bill.doctorName || "N/A"}
        </p>

        <hr />

        <h3>Medicines</h3>

        ${medicineRows
          ? `
<table
  style="
    width:100%;
    max-width:100%;
    table-layout:fixed;
    border-collapse:collapse;
    margin-top:10px;
  "
>
  <colgroup>
    <col style="width:40%;" />
    <col style="width:15%;" />
    <col style="width:20%;" />
    <col style="width:25%;" />
  </colgroup>

  <thead>
    <tr>
      <th style="border:1px solid #000;padding:8px;">
        Medicine
      </th>

      <th style="border:1px solid #000;padding:8px;">
        Quantity
      </th>

      <th style="border:1px solid #000;padding:8px;">
        Price
      </th>

      <th style="border:1px solid #000;padding:8px;">
        Amount
      </th>
    </tr>
  </thead>

  <tbody>
    ${medicineRows}
  </tbody>
</table>
            `
          : "<p>No medicines available</p>"
        }

        <hr />

        <h3 style="text-align:right;">
          Total Amount: ₹${bill.totalAmount || 0}
        </h3>

        <p>
          <b>Payment Mode:</b>
          ${bill.paymentMode || "N/A"}
        </p>

        <p>
          <b>Payment Status:</b>
          ${bill.paymentStatus || "N/A"}
        </p>

        <p>
          <b>Bill Date:</b>
          ${bill.createdAt
          ? new Date(bill.createdAt).toLocaleString("en-IN")
          : "N/A"
        }
        </p>

        <hr />

        <p style="text-align:center;">
          Generated By HMS
        </p>
      `;

   createPDF(
  element,
  `${patientData.name || "Patient"}_Pharmacy_Bill.pdf`,
  "portrait"
);
    } catch (error) {
      console.log("Pharmacy PDF Error:", error);

      if (error.response?.status === 404) {
        alert("Pharmacy bill not found for this patient");
      } else {
        alert("Failed to generate Pharmacy Bill PDF");
      }
    }
  };

  // =====================================================
  // NURSE PDF
  // =====================================================

  const downloadNursePDF = () => {
    if (!patient?._id) {
      alert("Patient data not available");
      return;
    }

    const nursingReports = patient.nursingReports || [];

    let reportRows = "";

    nursingReports.forEach((report, index) => {
      reportRows += `
      <tr>
        <td style="border:1px solid #000;padding:6px;">
          ${report.day || `Day ${index + 1}`}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.createdAt
          ? new Date(report.createdAt).toLocaleString("en-IN")
          : "N/A"}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.bp || "N/A"}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.pulse || "N/A"}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.temperature || "N/A"}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.spo2 || "N/A"}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.sugar || "N/A"}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.intake || "N/A"}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.output || "N/A"}
        </td>

        <td style="border:1px solid #000;padding:6px;">
          ${report.notes || "N/A"}
        </td>
      </tr>
    `;
    });

    const departmentData = `
    <h3>Nurse Daily Reports</h3>

    ${nursingReports.length > 0
        ? `
         <table
  style="
    width:100%;
    max-width:100%;
    table-layout:fixed;
    border-collapse:collapse;
    font-size:9px;
  "
>
            <thead>
              <tr>
                <th style="border:1px solid #000;padding:6px;">Day</th>
                <th style="border:1px solid #000;padding:6px;">Date & Time</th>
                <th style="border:1px solid #000;padding:6px;">BP</th>
                <th style="border:1px solid #000;padding:6px;">Pulse</th>
                <th style="border:1px solid #000;padding:6px;">Temperature</th>
                <th style="border:1px solid #000;padding:6px;">SpO2</th>
                <th style="border:1px solid #000;padding:6px;">Sugar</th>
                <th style="border:1px solid #000;padding:6px;">Intake</th>
                <th style="border:1px solid #000;padding:6px;">Output</th>
                <th style="border:1px solid #000;padding:6px;">Notes</th>
              </tr>
            </thead>

            <tbody>
              ${reportRows}
            </tbody>
          </table>
        `
        : "<p>No nursing reports available.</p>"
      }

    <br/>

    <h3>Nurse Notes</h3>

    <p>
      <b>Nurse Notes:</b>
      ${patient.nurseNotes || "N/A"}
    </p>

    <p>
      <b>Vitals:</b>
      ${patient.vitals || "N/A"}
    </p>
  `;

    generateLocalPDF(
      patient,
      "Nurse",
      departmentData,
      "landscape"
    );
  };

  // =====================================================
  // INSURANCE PDF
  // =====================================================

  const downloadInsurancePDF = () => {
    if (!patient) {
      alert("Patient data not available");
      return;
    }

    let departmentData = `
      <h3>Insurance Details</h3>

      <p>
        <b>Insurance Status:</b>
        ${patient.insuranceStatus || "N/A"}
      </p>

      <p>
        <b>Claim Number:</b>
        ${patient.claimNumber || "N/A"}
      </p>
    `;

    generateLocalPDF(patient, "Insurance", departmentData);
  };

  const createPDF = (element, filename, orientation = "portrait") => {
    const pageWidth =
      orientation === "landscape"
        ? "277mm"
        : "190mm";

    element.style.width = pageWidth;
    element.style.maxWidth = pageWidth;
    element.style.boxSizing = "border-box";
    element.style.margin = "0 auto";
    element.style.padding = "0";
    element.style.fontFamily = "Arial";
    element.style.overflow = "visible";

    const tables = element.querySelectorAll("table");

tables.forEach((table) => {
  table.style.width = "100%";
  table.style.maxWidth = "100%";
  table.style.tableLayout = "fixed";
  table.style.borderCollapse = "collapse";
  table.style.wordBreak = "break-word";
  table.style.overflowWrap = "anywhere";
  table.style.whiteSpace = "normal";
});

  const cells = element.querySelectorAll("th, td");

cells.forEach((cell) => {
  cell.style.wordBreak = "break-word";
  cell.style.overflowWrap = "anywhere";
  cell.style.whiteSpace = "normal";
  cell.style.boxSizing = "border-box";
});

html2pdf()
  .set({
    margin: 10,

    filename,

    image: {
      type: "jpeg",
      quality: 0.98,
    },

    html2canvas: {
      scale: 2,
      useCORS: true,
      logging: false,
    },

    pagebreak: {
      mode: ["css", "legacy"],
    },

    jsPDF: {
      unit: "mm",
      format: "a4",
      orientation,
    },
  })
  .from(element)
  .save();
};


  // =====================================================
  // GENERIC LOCAL PDF
  // =====================================================

  const generateLocalPDF = (
    patientData,
    name,
    departmentData,
    orientation = "portrait"
  ) => {
    const element = document.createElement("div");

    element.style.padding = "0";
    element.style.fontFamily = "Arial";

    element.innerHTML = `
      <h2 style="text-align:center;">
        ${name} PDF
      </h2>

      <hr />

      <h3>Patient Details</h3>

      <p>
        <b>UHID:</b>
        ${patientData.uhid || "N/A"}
      </p>

      <p>
        <b>Name:</b>
        ${patientData.name || "N/A"}
      </p>

      <p>
        <b>Age:</b>
        ${patientData.age || "N/A"}
      </p>

      <p>
        <b>Gender:</b>
        ${patientData.gender || "N/A"}
      </p>

      <p>
        <b>Mobile:</b>
        ${patientData.mobile || "N/A"}
      </p>

      <p>
        <b>Address:</b>
        ${patientData.address || "N/A"}
      </p>

      <hr />

      ${departmentData}

      <hr />

      <p style="text-align:center;">
        Generated By HMS
      </p>
    `;

    createPDF(
      element,
      `${patientData.name || "Patient"}_${name}.pdf`,
      orientation
    );
  };

  // =====================================================
  // MAIN CLICK HANDLER
  // =====================================================

  const downloadPDF = async () => {
    if (!patient) {
      alert("Patient data not available");
      return;
    }

    // =========================
    // LAB
    // =========================

    if (type === "lab") {
      downloadLabBillPDF();
      return;
    }

    // =========================
    // PHARMACY
    // =========================

    if (type === "pharmacy") {
      await downloadPharmacyPDF();
      return;
    }

    // =========================
    // DOCTOR
    // =========================

    if (type === "doctor") {
      downloadDoctorPDF();
      return;
    }

    // =========================
    // NURSE
    // =========================

    if (type === "nurse") {
      downloadNursePDF();
      return;
    }

    // =========================
    // INSURANCE
    // =========================

    if (type === "insurance") {
      downloadInsurancePDF();
      return;
    }

    alert("PDF type not supported");
  };

  return (
    <button
      className="btn btn-outline-success"
      onClick={downloadPDF}
      style={{ fontSize: "14px" }}
    >
      <b>{pdfname} PDF</b>
    </button>
  );
}

export default PdfCreate;
