import axios from "axios";
import html2pdf from "html2pdf.js";

function PdfCreate({ patient, pdfname, type }) {
  // =====================================================
  // DOCTOR PDF
  // =====================================================

  const downloadDoctorPDF = () => {
    if (!patient?._id) {
      alert("Patient data not available");
      return;
    }

    const pdfUrl = `http://localhost:5000/api/patient/${patient._id}/pdf`;

    window.open(pdfUrl, "_blank");
  };

  // =====================================================
  // PHARMACY PDF
  // =====================================================

  const downloadPharmacyPDF = async () => {
    if (!patient?._id) {
      alert("Patient data not available");
      return;
    }

    try {
      const res = await axios.get(
        `http://localhost:5000/api/pharmacy/bill/latest/${patient._id}`,
      );

      if (!res.data?.success || !res.data?.data) {
        alert("Pharmacy bill not found");
        return;
      }

      const bill = res.data.data;

      const patientData = bill.patientId || patient;

      let medicineRows = "";

      (bill.medicines || []).forEach((medicine) => {
        medicineRows += `
          <tr>
            <td style="border:1px solid #000;padding:8px;">
              ${medicine.medicineName || medicine.itemName || medicine.name || "N/A"}
            </td>

            <td style="border:1px solid #000;padding:8px;text-align:center;">
              ${medicine.quantity || 0}
            </td>

            <td style="border:1px solid #000;padding:8px;text-align:right;">
              ₹${medicine.price || medicine.unitPrice || 0}
            </td>

            <td style="border:1px solid #000;padding:8px;text-align:right;">
              ₹${medicine.amount || 0}
            </td>
          </tr>
        `;
      });

      const element = document.createElement("div");

      element.style.padding = "30px";
      element.style.fontFamily = "Arial";

      element.innerHTML = `
        <h2 style="text-align:center;">
          Pharmacy Bill
        </h2>

        <hr />

        <h3>Patient Details</h3>

        <p>
          <b>UHID:</b> ${patientData.uhid || "N/A"}
        </p>

        <p>
          <b>Name:</b> ${patientData.name || "N/A"}
        </p>

        <p>
          <b>Age:</b> ${patientData.age || "N/A"}
        </p>

        <p>
          <b>Gender:</b> ${patientData.gender || "N/A"}
        </p>

        <p>
          <b>Mobile:</b> ${patientData.mobile || "N/A"}
        </p>

        <p>
          <b>Doctor:</b> ${bill.doctorName || "N/A"}
        </p>

        <hr />

        <h3>Medicines</h3>

        ${
          medicineRows
            ? `
              <table
                style="
                  width:100%;
                  border-collapse:collapse;
                  margin-top:10px;
                "
              >
                <thead>
                  <tr>
                    <th style="border:1px solid #000;padding:8px;">
                      Medicine
                    </th>

                    <th style="border:1px solid #000;padding:8px;">
                      Quantity
                    </th>

                    <th style="border:1px solid #000;padding:8px;">
                      Price
                    </th>

                    <th style="border:1px solid #000;padding:8px;">
                      Amount
                    </th>
                  </tr>
                </thead>

                <tbody>
                  ${medicineRows}
                </tbody>
              </table>
            `
            : "<p>No medicines available</p>"
        }

        <hr />

        <h3 style="text-align:right;">
          Total Amount: ₹${bill.totalAmount || 0}
        </h3>

        <p>
          <b>Payment Mode:</b>
          ${bill.paymentMode || "N/A"}
        </p>

        <p>
          <b>Payment Status:</b>
          ${bill.paymentStatus || "N/A"}
        </p>

        <p>
          <b>Bill Date:</b>
          ${
            bill.createdAt
              ? new Date(bill.createdAt).toLocaleString("en-IN")
              : "N/A"
          }
        </p>

        <hr />

        <p style="text-align:center;">
          Generated By HMS
        </p>
      `;

      html2pdf()
        .set({
          margin: 10,

          filename: `${patientData.name || "Patient"}_Pharmacy_Bill.pdf`,

          image: {
            type: "jpeg",
            quality: 0.98,
          },

          html2canvas: {
            scale: 2,
          },

          jsPDF: {
            unit: "mm",
            format: "a4",
            orientation: "portrait",
          },
        })
        .from(element)
        .save();
    } catch (error) {
      console.log("Pharmacy PDF Error:", error);

      if (error.response?.status === 404) {
        alert("Pharmacy bill not found for this patient");
      } else {
        alert("Failed to generate Pharmacy Bill PDF");
      }
    }
  };

  // =====================================================
  // NURSE PDF
  // =====================================================

  const downloadNursePDF = () => {
    if (!patient) {
      alert("Patient data not available");
      return;
    }

    let departmentData = `
      <h3>Nurse Details</h3>

      <p>
        <b>Nurse Notes:</b>
        ${patient.nurseNotes || "N/A"}
      </p>

      <p>
        <b>Vitals:</b>
        ${patient.vitals || "N/A"}
      </p>
    `;

    generateLocalPDF(patient, "Nurse", departmentData);
  };

  // =====================================================
  // INSURANCE PDF
  // =====================================================

  const downloadInsurancePDF = () => {
    if (!patient) {
      alert("Patient data not available");
      return;
    }

    let departmentData = `
      <h3>Insurance Details</h3>

      <p>
        <b>Insurance Status:</b>
        ${patient.insuranceStatus || "N/A"}
      </p>

      <p>
        <b>Claim Number:</b>
        ${patient.claimNumber || "N/A"}
      </p>
    `;

    generateLocalPDF(patient, "Insurance", departmentData);
  };

  // =====================================================
  // GENERIC LOCAL PDF
  // =====================================================

  const generateLocalPDF = (patientData, name, departmentData) => {
    const element = document.createElement("div");

    element.style.padding = "30px";
    element.style.fontFamily = "Arial";

    element.innerHTML = `
      <h2 style="text-align:center;">
        ${name} PDF
      </h2>

      <hr />

      <h3>Patient Details</h3>

      <p>
        <b>UHID:</b>
        ${patientData.uhid || "N/A"}
      </p>

      <p>
        <b>Name:</b>
        ${patientData.name || "N/A"}
      </p>

      <p>
        <b>Age:</b>
        ${patientData.age || "N/A"}
      </p>

      <p>
        <b>Gender:</b>
        ${patientData.gender || "N/A"}
      </p>

      <p>
        <b>Mobile:</b>
        ${patientData.mobile || "N/A"}
      </p>

      <p>
        <b>Address:</b>
        ${patientData.address || "N/A"}
      </p>

      <hr />

      ${departmentData}

      <hr />

      <p style="text-align:center;">
        Generated By HMS
      </p>
    `;

    html2pdf()
      .set({
        margin: 10,

        filename: `${patientData.name || "Patient"}_${name}.pdf`,

        image: {
          type: "jpeg",
          quality: 0.98,
        },

        html2canvas: {
          scale: 2,
        },

        jsPDF: {
          unit: "mm",
          format: "a4",
          orientation: "portrait",
        },
      })
      .from(element)
      .save();
  };

  // =====================================================
  // MAIN CLICK HANDLER
  // =====================================================

  const downloadPDF = async () => {
    if (!patient) {
      alert("Patient data not available");
      return;
    }

    // =========================
    // PHARMACY
    // =========================

    if (type === "pharmacy") {
      await downloadPharmacyPDF();
      return;
    }

    // =========================
    // DOCTOR
    // =========================

    if (type === "doctor") {
      downloadDoctorPDF();
      return;
    }

    // =========================
    // NURSE
    // =========================

    if (type === "nurse") {
      downloadNursePDF();
      return;
    }

    // =========================
    // INSURANCE
    // =========================

    if (type === "insurance") {
      downloadInsurancePDF();
      return;
    }

    alert("PDF type not supported");
  };

  return (
    <button
      className="btn btn-outline-success"
      onClick={downloadPDF}
      style={{ fontSize: "14px" }}
    >
      <b>{pdfname} PDF</b>
    </button>
  );
}

export default PdfCreate;
